<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:figaf="http://figaf.com/cpi" xmlns:ifl="http:///com.sap.ifl.model/Ifl.xsd" xmlns:ns2="http://sap.com/xi/BASIS" version="2.0">
    <xsl:output indent="yes"/>

    <xsl:param name="iflowTechnicalName"/>
    <xsl:param name="iflowDisplayedName"/>
    <xsl:param name="packageTechnicalName"/>
    <xsl:param name="packageDisplayedName"/>

    <xsl:template match="ns2:CommunicationChannel">
        <figaf:Block>
            <Name>SFTP</Name>
            <ExtensionElements>
                <ifl:property>
                    <key>disconnect</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>fileName</key>
                    <value>{{target_filename}}</value>
                </ifl:property>
                <ifl:property>
                    <key>Description</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>maximumReconnectAttempts</key>
                    <value>3</value>
                </ifl:property>
                <ifl:property>
                    <key>stepwise</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>fileExist</key>
                    <value>Ignore</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentNS</key>
                    <value>sap</value>
                </ifl:property>
                <ifl:property>
                    <key>autoCreate</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>location_id</key>
                    <value>{{location_id}}</value>
                </ifl:property>
                <ifl:property>
                    <key>Name</key>
                    <value>FTP</value>
                </ifl:property>
                <ifl:property>
                    <key>TransportProtocolVersion</key>
                    <value>1.2.0</value>
                </ifl:property>
                <ifl:property>
                    <key>flatten</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>sftpSecEnabled</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>useTempFile</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentSWCVName</key>
                    <value>external</value>
                </ifl:property>
                <ifl:property>
                    <key>path</key>
                    <value>{{target_directory}}</value>
                </ifl:property>
                <ifl:property>
                    <key>encryption</key>
                    <value>ftpes</value>
                </ifl:property>
                <ifl:property>
                    <key>host</key>
                    <value>{{ftp_host}}</value>
                </ifl:property>
                <ifl:property>
                    <key>connectTimeout</key>
                    <value>10000</value>
                </ifl:property>
                <ifl:property>
                    <key>MessageProtocol</key>
                    <value>File</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentSWCVId</key>
                    <value>1.2.0</value>
                </ifl:property>
                <ifl:property>
                    <key>direction</key>
                    <value>Receiver</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentType</key>
                    <value>FTP</value>
                </ifl:property>
                <ifl:property>
                    <key>fileAppendTimeStamp</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>credential_name</key>
                    <value>{{ftp_sapuser}}</value>
                </ifl:property>
                <ifl:property>
                    <key>proxyType</key>
                    <value>{{connectiontype}}</value>
                </ifl:property>
                <ifl:property>
                    <key>componentVersion</key>
                    <value>1.1</value>
                </ifl:property>
                <ifl:property>
                    <key>reconnectDelay</key>
                    <value>1000</value>
                </ifl:property>
                <ifl:property>
                    <key>system</key>
                    <value>Receiver</value>
                </ifl:property>
                <ifl:property>
                    <key>tempFileName</key>
                    <value>${file:name}.tmp</value>
                </ifl:property>
                <ifl:property>
                    <key>TransportProtocol</key>
                    <value>FTP</value>
                </ifl:property>
                <ifl:property>
                    <key>cmdVariantUri</key>
                    <value>ctype::AdapterVariant/cname::sap:FTP/tp::FTP/mp::File/direction::Receiver/version::1.1.4</value>
                </ifl:property>
                <ifl:property>
                    <key>MessageProtocolVersion</key>
                    <value>1.2.0</value>
                </ifl:property>
            </ExtensionElements>
            <ExternalProperties>
                <!-- If you want to select content from the Channel, you can use an XPath like this:-->
                <!-- <xsl:value-of select="AdapterSpecificAttribute[Name='host']/Value"/>-->
                <item>
                    <name>target_filename</name>
                    <value><xsl:value-of select="AdapterSpecificAttribute[Name='file.targetFileName']/Value"/></value>
                </item>
                <item>
                    <name>location_id</name>
                    <value></value>
                </item>
                <item>
                    <name>target_directory</name>
                    <value><xsl:value-of select="AdapterSpecificAttribute[Name='file.targetDir' or Name='ftp.targetDir']/Value"/></value>
                </item>
                <item>
                    <name>ftp_host</name>
                    <value><xsl:value-of select="AdapterSpecificAttribute[Name='ftp.host']/Value"/>:<xsl:value-of select="AdapterSpecificAttribute[Name='ftp.port']/Value"/></value>
                </item>
                <item>
                    <name>ftp_sapuser</name>
                    <value><xsl:value-of select="CommunicationChannelID/ComponentID"/>_USER</value>
                </item>
                <item>
                    <name>connectiontype</name>
                    <value>sapcc</value>
                </item>
            </ExternalProperties>
            <Notifications>
                <ManualActionRequired>Check FTPS connection and cloud connector settings</ManualActionRequired>
                <Advice>Check FTP username <xsl:value-of select="CommunicationChannelID/ComponentID"/>_USER</Advice>
            </Notifications>
        </figaf:Block>
    </xsl:template>
</xsl:stylesheet>