<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  xmlns:ns2="http://sap.com/xi/BASIS" xmlns:figaf="http://figaf.com/cpi" xmlns:ifl="http:///com.sap.ifl.model/Ifl.xsd" >
    <xsl:output indent="yes"/>
    <xsl:template match="ns2:CommunicationChannel">
        <figaf:Block>
            <Name>SOAP</Name>
            <ExtensionElements>
                 <ifl:property>
                    <key>cleanupHeaders</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>WsdlUserNameTokenCredentialName</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>privateKeyAlias</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>location_id</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>Name</key>
                    <value>SOAP</value>
                </ifl:property>
                <ifl:property>
                    <key>TransportProtocolVersion</key>
                    <value>1.10.0</value>
                </ifl:property>
                <ifl:property>
                    <key>UserNameTokenOption</key>
                    <value>None</value>
                </ifl:property>
                <ifl:property>
                    <key>proxyPort</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>WSSecurity_SignatureAlgorithm</key>
                    <value>SHA1</value>
                </ifl:property>
                <ifl:property>
                    <key>recipientX509TokenAssertion</key>
                    <value>WssX509V3Token10</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentSWCVId</key>
                    <value>1.10.0</value>
                </ifl:property>
                <ifl:property>
                    <key>X509TokenAssertion</key>
                    <value>WssX509V3Token10</value>
                </ifl:property>
                <ifl:property>
                    <key>allowChunking</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>soapWsdlPortName</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>componentVersion</key>
                    <value>1.10</value>
                </ifl:property>
                <ifl:property>
                    <key>proxyHost</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>system</key>
                    <value>AsyncPartner_B2B</value>
                </ifl:property>
                <ifl:property>
                    <key>SenderBasicSecurityProfileCompliant</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>UserNameTokenCredentialName</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>AlgorithmSuiteAssertion</key>
                    <value>Basic128Rsa15</value>
                </ifl:property>
                <ifl:property>
                    <key>TransportProtocol</key>
                    <value>HTTP</value>
                </ifl:property>
                <ifl:property>
                    <key>cmdVariantUri</key>
                    <value>ctype::AdapterVariant/cname::sap:SOAP/tp::HTTP/mp::SOAP 1.x/direction::Receiver/version::1.10.0</value>
                </ifl:property>
                <ifl:property>
                    <key>MessageProtocolVersion</key>
                    <value>1.10.0</value>
                </ifl:property>
                <ifl:property>
                    <key>Description</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>WSSecurityType_outbound</key>
                    <value>SignMessage</value>
                </ifl:property>
                <ifl:property>
                    <key>InitiatorTokenIncludeStrategy_outbound</key>
                    <value>AlwaysToRecipient</value>
                </ifl:property>
                <ifl:property>
                    <key>SetTimeStamp</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentNS</key>
                    <value>sap</value>
                </ifl:property>
                <ifl:property>
                    <key>ComponentSWCVName</key>
                    <value>external</value>
                </ifl:property>
                <ifl:property>
                    <key>PublicKeyAliasEncryption_wsdl</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>soapWsdlURL</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>CompressMessage</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>sendHttpResponseCode</key>
                    <value>0</value>
                </ifl:property>
                <ifl:property>
                    <key>soapServiceName</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>MessageProtocol</key>
                    <value>SOAP 1.x</value>
                </ifl:property>
                <ifl:property>
                    <key>requestTimeout</key>
                    <value>60000</value>
                </ifl:property>
                <ifl:property>
                    <key>direction</key>
                    <value>Receiver</value>
                </ifl:property>
                <ifl:property>
                    <key>authentication</key>
                    <value>Basic</value>
                </ifl:property>
                <ifl:property>
                    <key>PrivateKeyAliasSigning</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>ComponentType</key>
                    <value>SOAP</value>
                </ifl:property>
                <ifl:property>
                    <key>address</key>
                    <value>{{SOAP_URL}}</value>
                </ifl:property>
                <ifl:property>
                    <key>SenderBasicSecurityProfileCompliant_wsdl</key>
                    <value>1</value>
                </ifl:property>
                <ifl:property>
                    <key>proxyType</key>
                    <value>default</value>
                </ifl:property>
                <ifl:property>
                    <key>operationName</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>PrivateKeyAliasSigning_wsdl</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>PublicKeyAliasEncryption</key>
                    <value/>
                </ifl:property>
                <ifl:property>
                    <key>WSSecurity_outbound</key>
                    <value>None</value>
                </ifl:property>
                <ifl:property>
                    <key>RecipientTokenIncludeStrategy</key>
                    <value>Never</value>
                </ifl:property>
                <ifl:property>
                    <key>credentialName</key>
                    <value>{{SOAP_User}}</value>
                </ifl:property>
                <ifl:property>
                    <key>Layout_outbound</key>
                    <value>Strict</value>
                </ifl:property>
            </ExtensionElements>
            <ExternalProperties>
                <item>
                    <name>SOAP_URL</name>
                    <value><xsl:value-of select="AdapterSpecificAttribute[Name='XMBWS.TargetURL']/Value"/></value>
                </item>
				
				 <item>
                    <name>SOAP_User</name>
                    <value><xsl:value-of select="AdapterSpecificAttribute[Name='XMBWS.User']/Value"/></value>
                </item>
            </ExternalProperties>
            <Notifications>
                <ManualActionRequired>Add User credentials <xsl:value-of select="AdapterSpecificAttribute[Name='XMBWS.User']/Value"/></ManualActionRequired>
            </Notifications>
        </figaf:Block>
    </xsl:template>
</xsl:stylesheet>